### ISSUE TITLE
Migration fails due to self signed certificate

### ISSUE THREAD

**Issue by ChristianAE** [gogits/go-gogs-client#14]
I am currently using a self hosted instance of Stash for my repositories.

Trying gogs it would be crucial for me to migrate all my repositories. At the moment these fails due to a self signed certificate I am using. Is there a way around it? I could only find a "SKIP_VERIFY" option for the Mailer.

> Migration failed: Clone: exit status 128 - fatal: unable to access 'https://<credentials>@URL_TO_HOST:443/scm/go/my_repository.git/': SSL certificate problem: self signed certificate

**Comment by Unknwon** [comment]
Thanks your feedback!

I think this is duplicated to https://github.com/gogits/gogs/issues/2089
