### ISSUE TITLE
Issues API

### ISSUE THREAD

**Issue by iwanbk** [gogits/go-gogs-client#25]
As mentioned in my comment (https://github.com/gogits/gogs/issues/1692#issuecomment-206590786), i'd like to implement issues API, started with comments part.

Please let me know if there is someone already working on it.

If not, i will come with API specification proposal.

**Comment by Wikunia** [comment]
I would like to have some parameters like searching for issues.
Getting all closed issues or all issues or all issues with one of ... labels.
At the moment only open issues can be displayed, right?
