### ISSUE TITLE
CSRF Token Issues

### ISSUE THREAD

**Issue by wyattjoh** [gogits/go-gogs-client#3]
Currently, I can't see a way of interacting with my gogs server when I keep getting:

```Bad Request: no CSRF token represnet```

Whenever I try to create a repository via the API.

**Comment by Unknwon** [comment]
Hi @wyattjoh , I've saw this when I write dcos about APIs, but should be fixed in `master` branch, not sure if you're willing to update Gogs.

**Comment by Unknwon** [comment]
Any updates on this?
