### ISSUE TITLE
Gogs REST API

### ISSUE THREAD

**Issue by nasali** [gogits/go-gogs-client#5]
Hi there,

It's great that I'm able to make a POST HTTP request to the REST API that Gogs exposes to create a repository and all that, but I can't seem to find documentation on how to go about deleting a repository that was created via the same interface.

Is that just not documented? Or is it not supported via the currently exposed REST API?

Thanks a bunch!

**Comment by Unknwon** [comment]
Hmm.. all docs are here in Wiki: https://github.com/gogits/go-gogs-client/wiki

**Comment by nasali** [comment]
@Unknwon Thank you for the prompt reply, I appreciate it.

So, using the documentation you provided, I am able to create a repo via a POST like so:
```
$ curl -H 'Accept:application/json' -H 'Content-Type:application/json' -H 'Authorization: Basic bmFzczpwYXNz' -d '{"name":"SomeAmazingRepo"}' -X POST https://dev.myserver.com:10080/api/v1/user/repos
{
 "id": 20,
 "owner": {
   "id": 1,
   "username": "nass",
   "full_name": "",
   "email": "nasali@anypresence.com",
   "avatar_url": "//1.gravatar.com/avatar/abdb83fbee6662589eae168c3f6e6669"
 },
 "full_name": "nass/SomeAmazingRepo",
 "private": false,
 "fork": false,
 "html_url": "https://dev.myserver.com:10080/nass/SomeAmazingRepo",
 "clone_url": "https://dev.myserver.com:10080/nass/someamazingrepo.git",
 "ssh_url": "ssh://git@dev.myserver.com:10022/nass/someamazingrepo.git",
 "permissions": {
   "admin": true,
   "push": true,
   "pull": true
 }
}
```

How do I make a REST call to delete the repo?

**Comment by Unknwon** [comment]
> How do I make a REST call to delete the repo?

Not implemented yet, but I can make it :sweat_smile:

**Comment by nasali** [comment]
Thank you! I would appreciate that very much.

How do I make a REST call to add a user as a collaborator to my repository? Is that also not implemented?

**Comment by Unknwon** [comment]
@nasali yeah, many APIs are missing, most of implemented ones are because internally need that. And yes if you make request, will have higher priority to implement them first.

**Comment by nasali** [comment]
Okay, good to know that. 

How do I make a request to have the complete set of CRUD operations exposed on repository, user, collaborator and org via the REST API then?

**Comment by Unknwon** [comment]
It certainly takes time, you can make an issue which contains a checklist of API endpoints you want to  https://github.com/gogits/gogs/issues

**Comment by nasali** [comment]
Done. https://github.com/gogits/gogs/issues/1692
Thanks again!
