### ISSUE TITLE
Error on Repositories Wiki page

### ISSUE THREAD

**Issue by tomekwojcik** [gogits/go-gogs-client#6]
Hello,
the wiki page describing repositories endpoints incorrectly states that in order to create an organization repository, one should use the `POST /orgs/:org/repos` while in reality the endpoint is `POST /org/:org/repos` :).

**Comment by Unknwon** [comment]
Thanks! You're right, fixed. :sweat_smile:

**Comment by tomekwojcik** [comment]
Cheers! 😃
