### ISSUE TITLE
richer api

### ISSUE THREAD

**Issue by jmls** [gogits/go-gogs-client#68]
I'm wanting to move away from gitlab (slow, slow, slow) but have an application that uses the api to manage lots of things. From what I can see, the api in gogs is a very poor relation - are there any plans on beefing up the api and making it much more functionally rich ?

**Comment by Unknwon** [comment]
Yes, all APIs will be done before 1.0 release.

**Comment by jmls** [comment]
that's great news - but when is the 1.0 release due ? ;)

**Comment by Unknwon** [comment]
No timeline unless you fund :smile:
