### ISSUE TITLE
Get Repo by Name

### ISSUE THREAD

**Issue by bradrydzewski** [gogits/go-gogs-client#7]
Would it be possible to add an endpoint for getting a single repository? I'm working on integrating Gogs with the latest version of Drone (0.4) and we have the need to retrieve a Repo by name.

If you have any docs for your API you can point me to I'm happy to submit a pull request and add this functionality to the client.

**Comment by Unknwon** [comment]
> Would it be possible to add an endpoint for getting a single repository?

Yes, let me work on it right now.

**Comment by bradrydzewski** [comment]
by the way, I recently installed Gogs and just wanted to say how great it is. really impressive work

**Comment by Unknwon** [comment]
:smiley: Glad you like it!

Just to make sure that what specific fields of repository does Drone need?

**Comment by bradrydzewski** [comment]
@Unknwon the exact same struct you have for the repository list, including the `Permissions`, would be exactly what I'm looking for. thanks!

```
type Repository struct {
	Id          int64      `json:"id"`
	Owner       User       `json:"owner"`
	FullName    string     `json:"full_name"`
	Private     bool       `json:"private"`
	Fork        bool       `json:"fork"`
	HtmlUrl     string     `json:"html_url"`
	CloneUrl    string     `json:"clone_url"`
	SshUrl      string     `json:"ssh_url"`
	Permissions Permission `json:"permissions"`
}
```

**Comment by Unknwon** [comment]
OK, I've pushed https://github.com/gogits/gogs/commit/35a65736fa1361d1d0fb83217f95d7aa8ca71336 to `master` branch of Gogs, and updated client lib as well.

**Comment by Unknwon** [comment]
Ping me if you have any other problem/question.

**Comment by bradrydzewski** [comment]
great thanks

**Comment by Unknwon** [comment]
:trollface:
