### ISSUE TITLE
Enable setting custom client, InsecureSkipVerify

### ISSUE THREAD

**Issue by bradrydzewski** [gogits/go-gogs-client#8]
For GitLab we see a lot of people self-hosting with customer SSL certs. We typically have to set `InsecureSkipVerify` to true. This is probably something we'll want to support with the Gogs client as well.

Something like this:

```Go
tr := &http.Transport{
  TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
}
client := &http.Client{Transport: tr}

gogs.NewClient(url, token, client)
```

**Comment by Unknwon** [comment]
You can now use https://github.com/gogits/go-gogs-client/commit/8068507b500ea3ededecacc9d53c10da5f6ddd01#diff-0ec5cf868d4c7c045eb43e57a1b06419R37 to set user defined `http.Client`.

**Comment by michaelgibson** [comment]
This was merged into drone here: https://github.com/drone/drone/pull/1433
Can probably close this.

**Comment by Unknwon** [comment]
@michaelgibson thanks for letting me know!
